[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "collection"
    name = "Collection"
    url = "/collection"
    weight = 3

[[main]]
    identifier = "corner"
    name = "Corner"
    url = "/corner"
    weight = 4
