# Homepage Config
isSinglePage = true

# Meta Config
description = "Kamaboko Home | 鱼糕的树屋"

# Header Configuration
avatar = "img/profile-picture.jpg"

#favicon
favicon = "favicon_v2.ico"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

# giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]       
    enable = false
    repo = ""
    repoId = ""
    category = "Announcements"
    categoryId = ""
    # mapping = "pathname"  # comment value is the default value
    # strict = 0
    # reactionsEnabled = 1
    # emitMetadata = 0
    # inputPosition = "top"
    # theme = "light"
    # lang = "zh-CN"
    # lazyLoading = true
